### DISCUSSION TITLE
Deploying Iris using portqiner

### DISCUSSION THREAD

**Discussion by IOTech17** [dfir-iris/iris-web#384] [Q&A]
Hi

I am trying to use portainer to deploy Iris.

I am following the main steps from the read me

#  Clone the iris-web repository
git clone https://github.com/dfir-iris/iris-web.git
cd iris-web

# Checkout to the last tagged version 
git checkout v2.3.7

# Copy the environment file 
cp .env.model .env

# Build the dockers
docker-compose build

However I do not modify the .env file default value, instead once the image is built I am using portainer stack to deploy Iris using a docker compose file

```
version: "3.5"
services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: iriswebapp_rabbitmq
      networks:
        - iris_backend

  db:
    container_name: iriswebapp_db
    image: iriswebapp_db:v2.3.7
    restart: always
    # Used for debugging purposes, should be deleted for production
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_ADMIN_USER
      - POSTGRES_ADMIN_PASSWORD
      - POSTGRES_DB
    networks:
      - iris_backend
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - stack.env  

  app:
    image: iriswebapp_app:v2.3.7
    container_name: iriswebapp_app
    command: ['nohup', './iris-entrypoint.sh', 'iriswebapp']
    privileged: true
    volumes:
      # RootCA necessary when dealing with an auth server without a trusted CA signed certificate
      - /path/iris-web/certificates/rootCA/irisRootCACert.pem:/etc/irisRootCACert.pem:ro
      - /path/iris-web/certificates/:/home/iris/certificates/:ro
      - /path/iris-web/certificates/ldap/:/iriswebapp/certificates/ldap/:ro
      - iris-downloads:/home/iris/downloads
      - user_templates:/home/iris/user_templates
      - server_data:/home/iris/server_data
    restart: always
    depends_on:
      - "rabbitmq"
      - "db"
    # Used for debugging purposes, should be deleted for production
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - stack.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_ADMIN_USER
      - POSTGRES_ADMIN_PASSWORD
      - POSTGRES_SERVER
      - POSTGRES_PORT
      - DOCKERIZED
      - IRIS_SECRET_KEY
      - IRIS_SECURITY_PASSWORD_SALT
    networks:
      - iris_backend
      - iris_frontend

  worker:
    image: iriswebapp_app:v2.3.7
    container_name: iriswebapp_worker
    privileged: true
    command: ['./wait-for-iriswebapp.sh', 'app:8000', './iris-entrypoint.sh', 'iris-worker']
    volumes:
      - /path/iris-web/certificates/rootCA/irisRootCACert.pem:/etc/irisRootCACert.pem:ro
      - /path/iris-web/certificates/:/home/iris/certificates/:ro
      - /path/iris-web/certificates/ldap/:/iriswebapp/certificates/ldap/:ro
      - iris-downloads:/home/iris/downloads
      - user_templates:/home/iris/user_templates
      - server_data:/home/iris/server_data
    depends_on:
      - "rabbitmq"
      - "db"
      - "app"
    env_file:
      - stack.env
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_ADMIN_USER
      - POSTGRES_ADMIN_PASSWORD
      - POSTGRES_SERVER
      - POSTGRES_PORT
      - DOCKERIZED
      - IRIS_SECRET_KEY
      - IRIS_SECURITY_PASSWORD_SALT
      - IRIS_WORKER
    networks:
      - iris_backend

  nginx:
    image: iriswebapp_nginx:v2.3.7
    container_name: iriswebapp_nginx
    privileged: true
    environment:
      - IRIS_UPSTREAM_SERVER
      - IRIS_UPSTREAM_PORT
      - INTERFACE_HTTPS_PORT
      - SERVER_NAME
      - CERT_FILENAME
      - KEY_FILENAME
      - IRIS_AUTHENTICATION_TYPE
    networks:
      - iris_frontend
    ports:
      - "444:${INTERFACE_HTTPS_PORT:-443}"
    volumes:
      - "/path/iris-web/certificates/web_certificates/:/www/certs/:ro"
    env_file:
      - stack.env
    restart: on-failure:5
    depends_on:
      - "app"

volumes:
  iris-downloads:
  user_templates:
  server_data:
  db_data:

networks:
  iris_backend:
    name: iris_backend
  iris_frontend:
    name: iris_frontend

```
As you can see I am calling the env value via    

 env_file:
      - stack.env

However I get an error for the db admin password ( I changed both user and password, it seems to be passed on to the container as the error mention the name of the user I changed via the env file).

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "username"

I am using the very latest version of docker and the host is a fedora core os instance.

Thank you
