### ISSUE TITLE
API v2 note create

### ISSUE THREAD

**Issue by c8y3** [dfir-iris/iris-web#717]
Implement endpoint POST /api/v2/cases/{case_identifier}/notes to create a note.

* [x] return 201 in case of success
* [x] if the case is not found, return 404
* [x] if the directory does not exist, return 400
* [x] create method in the business layer
* [x] check returned object is uniform with other endpoints
* [x] deprecate POST /case/notes/add
* [x] openapi: document endpoint
* [x] openapi: deprecate POST /case/notes/add

**Comment by c8y3** [comment]
* [x] add:
  ```
      if not cases_exists(case_identifier):
          return response_api_not_found()
  ```
* [x] document 404 return, when case is not found
* [x] document and test field `modification_history` in `Note`
  ```
  modification_history:
    type: object
  ...
  modification_history:
    '1711563261.268616':
      user: administrator
      user_id: 1
      action: created note
  ```
* [x]  if the directory belongs to another case, return 400
